### ISSUE TITLE
Rayan you're a G

### ISSUE THREAD

**Issue by c12n** [iRayanKhan/TanaraSign#1]
Great app

**Comment by andrepcg** [comment]
not suspicious at all

**Comment by iRayanKhan** [comment]
> not suspicious at all

Well Mr.Ruby dev, if you are so good at Swift, why don't we hold hands, hop in vc, and review every single bit of code line by line. :)

**Comment by andrepcg** [comment]
I would still not install it. I think this is the type of software that needs to be open sourced for it to be credible. I may understand you're keeping it closed source but then you also know you'll get less installs and people participating. Have a good one

**Comment by iRayanKhan** [comment]
Link a completely local on-device signing tool that is open source then. 

How come ESign, Scarlet, GBox, etc are all fine being closed source, yet a dev like me can't?
