### ISSUE TITLE
apple watch sideloading not wroking

### ISSUE THREAD

**Issue by emoji987** [iRayanKhan/TanaraSign#2]
i cannot sideload on my apple watch it says that it could not verify the integrity of the app thx for helping and nice app

**Comment by iRayanKhan** [comment]
> i cannot sideload on my apple watch it says that it could not verify the integrity of the app thx for helping and nice app

Thanks for the feedback. There is currently a bug in the Watch app between syncing. This doesn't affect signing, however in the next patch it should fix the issues and shouldn't need any more updates. 

For signing ensure you have a paid dev account, I haven't had the chance to test without one. You also need a Mac with Xcode, iOS App Signer, and Apple Configurator. To clarify, do you see integrity error on both the phone and watch, or just phone? I will post instructions on installation once the final patch is out.

**Comment by emoji987** [comment]
Im using a dev certificate and i only have my iphone at my disposal at the moment. The error appear on the watch i have no problem on the phone.

Cannot wait to see the instruction ! The app look nice and works perfectly appart of this bug

**Comment by bradleytechman** [comment]
> i cannot sideload on my apple watch it says that it could not verify the integrity of the app thx for helping and nice app

Same issue

**Comment by emoji987** [comment]
> > i cannot sideload on my apple watch it says that it could not verify the integrity of the app thx for helping and nice app
> 
> Same issue

Do you have your own dev account or you bought a certificate ?

**Comment by bradleytechman** [comment]
> > > i cannot sideload on my apple watch it says that it could not verify the integrity of the app thx for helping and nice app
> 
> > 
> 
> > Same issue
> 
> 
> 
> Do you have your own dev account or you bought a certificate ?

Bought a certificate

**Comment by emoji987** [comment]
> > > > i cannot sideload on my apple watch it says that it could not verify the integrity of the app thx for helping and nice app
> > 
> > 
> > > 
> > 
> > 
> > > Same issue
> > 
> > 
> > Do you have your own dev account or you bought a certificate ?
> 
> Bought a certificate

Yeah so that's why i just figured it out, when you buy a a certificate it links per device, it means all the ipa u'll sign will only work on your iPhone and not on any other device u'll need to buy another certificate for your apple watch

**Comment by bradleytechman** [comment]
> > > > > i cannot sideload on my apple watch it says that it could not verify the integrity of the app thx for helping and nice app
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Same issue
> 
> > > 
> 
> > > 
> 
> > > Do you have your own dev account or you bought a certificate ?
> 
> > 
> 
> > Bought a certificate
> 
> 
> 
> Yeah so that's why i just figured it out, when you buy a a certificate it links per device, it means all the ipa u'll sign will only work on your iPhone and not on any other device u'll need to buy another certificate for your apple watch

Makes sense. My uncle should have a dev account so i'll see if I can use that. And if your wondering it's for the app he's working on, not sideloading

**Comment by iRayanKhan** [comment]
Yes, a developer account is required to sign the Watch app. 

The iOS and Watch app must be signed with the same dev account.

**Comment by iRayanKhan** [comment]
Upon further investigation, Apple seems to have patched the watch side loading method without Xcode. 
This project is reaching EOL, (it still works), but I do not have plans to open source this project so at the moment there is no installation method.
