### ISSUE TITLE
App crashes upon attempting to sign a app from certain sources

### ISSUE THREAD

**Issue by bradleytechman** [iRayanKhan/TanaraSign#3]
When I try to sideload an app from certain sources, the app crashes.

**Comment by iRayanKhan** [comment]
If the repository has the versions nested (ie it isn't showing anything in the detail view), this is a known issue. I didn't realize there was 2 formats to AltStore repositories. This will be resolved in the next patch (hopefully). 

If you don't mind sending an email to webmaster at 00p1um.tools, with the url to the repos in question, I will investigate further.

**Comment by iRayanKhan** [comment]
@bradleytechman I have tested a repository and have fixed the issue. The final build (next release) will have this fix submitted.

**Comment by bradleytechman** [comment]
> @bradleytechman I have tested a repository and have fixed the issue. The final build (next release) will have this fix submitted. 

Alright, Thank you! I actually wasn't aware there's two formats of AltStore sources.

**Comment by JumpIn-Git** [comment]
> If the repository has the versions nested (ie it isn't showing anything in the detail view), this is a known issue. I didn't realize there was 2 formats to AltStore repositories. This will be resolved in the next patch (hopefully).
> 
> If you don't mind sending an email to webmaster at 00p1um.tools, with the url to the repos in question, I will investigate further.

ok so i tryed tanarasign a few months ago and it didnt work, i want to try i again. is the tanarasign.ipa file the newest release or do i get the new one from somewhere else?

**Comment by iRayanKhan** [comment]
The current ipa doesn't have the renewed ssl certificate. I'll seed a new ipa this weekend.

**Comment by JumpIn-Git** [comment]
> The current ipa doesn't have the renewed ssl certificate. I'll seed a new ipa this weekend.

wait what do u meaan seed? is the new releases able to download from other sources?
